global_costmap:
   global_frame: map #对于全局代价地图，使用/map作为全局坐标
   robot_base_frame: base_link
   update_frequency: 3.0 #更新频率
   publish_frequency: 3.0  #发布频率
   static_map: true #静态地图
   rolling_window: false #滚动窗口
   resolution: 0.05 #分辨率
   transform_tolerance: 1.0 #转换容差
   map_type: costmap #有两种类型：“voxel”和“costmap”，“voxel”表示3D视图，“costmap”表示2D视图
   plugins:
    # - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}
     - {name: static_layer, type: "costmap_2d::StaticLayer"} 
   
     - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
   inflation_layer: 
      inflation_radius: 0.51
