local_costmap:
   global_frame: map
   robot_base_frame: base_footprint
   update_frequency: 3.0
   publish_frequency: 3.0 #发布信息的频率
   static_map: false
   rolling_window: true #用于0配置在机器人运动过程中，代价地图始终以机器人为中心
   width: 4.0 #配置代价地图的尺寸，以米为单位
   height: 4.0 #配置代价地图的尺寸，以米为单位
   resolution: 0.05 #配置代价地图的分辨率，以米为单位
   transform_tolerance: 0.5 #在tf树坐标之间转换的允许延时或者绘图过程临时被中止的允许延时，以秒为单位
   map_type: costmap
   plugins:
     - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}
#     - {name: social_layer,        type: "social_navigation_layers::ProxemicLayer"}   
#     - {name: social_pass_layer,        type: "social_navigation_layers::PassingLayer"}  
     #- {name: static_layer, type: "costmap_2d::StaticLayer"} 
     - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
 
  #Configuration for the sensors that the costmap will use to update a map   
   obstacle_layer:
     observation_sources: scan  
     scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0} 
   inflation_layer: 
      inflation_radius: 0.1
      cost_scaling_factor: 10
